#### Homework 1 ####


### Preliminaries ###
rm(list = ls())

# Set your working directory to the "Data" folder associated with this
# assignment:
setwd("~/Desktop")

# Load in the data we will be using:
load("Workshop_12-Synthetic_Tweets.RData")

# This synthetic dataset was generated by collecting all tweets that mentioned
# either "Trump" or "POTUS" (President Of The United States) over a 5 minute
# period around noon on Thursday, May 18th, 2017. The data were then scrubbed of
# Twitter usernames (except for President Trump), and had their metadata altered
# as well. In this assignment, you will be asked to use 'for()'
# loops, 'if()' statements, and to write your own functions to count the number
# of synthetic tweets that meet a number of different conditions.

# In order for this to be interesting, we are going to introduce one more
# base R function that will allow us to search for words in a string. This
# function is called 'grepl()', and returns a logical (TRUE/FALSE) depending on
# whether it finds a search pattern in the given string. Lets look at an
# example:
my_string <- "Hello, my name is Matt and programming is fun!"

# Lets see if this string contains the word "is":
grepl("is", my_string) # returns TRUE

# Now lets see if it contains the word "orange":
grepl("orange", my_string) # returns FALSE

# What about "matt"?
grepl("matt", my_string) # returns FALSE

# But the original string contained "matt", it was just capitalized. To ignore
# the case of words, we can set an option in 'grepl()', which we will use in
# the rest of this assignment:
grepl("matt", my_string, ignore.case = TRUE) # returns TRUE



### Exercise 1 ###

# In this exercise, you are going to use a 'for()' loop and an 'if()' statment
# to count the number of tweets that contain the word "POTUS" (case insensitive)
# in the their main text. You can access the text field for a give tweet (in
# this case, the first row in the dataset), using the following line of code:
print(synthetic_tweets$text[1])

# remember, we can use a variable to index the rows:
i <- 1
print(synthetic_tweets$text[i])

# The last bit of example code you will need is to put this inside of a 'grepl()'
# call:
i <- 1
grepl("POTUS", synthetic_tweets$text[i], ignore.case = TRUE)

# Okay, so I will get you started here. Store the count of the number of tweets
# that mention "POTUS" in a variable:
POTUS_Tweets_Count <- 0

# Now loop over the dataset and use an if statment to check and see if the text
# field in each tweet contains the string "POTUS" and add 1 to the value of
# POTUS_Tweets_Count if 'grepl()' returns TRUE



### Exercise 2 ###

# Now try to find all tweets that contain both the term "Trump" (case
# insensitive) and "Comey" (also case insensitive). You can do this using
# nested if statements like this:
# if (tweet contains "Trump") {
#   if (tweet contains "Comey") {
#       increment count
#   }
# }



### Exercise 3 ###

# Write a function that returns the 'screen_name' of all users who have a
# specified number of 'statuses_count', 'followers_count', and
# 'favourites_count'. Do this only using 'for()' loops and 'if()' statements.
# Here is a template for the function:

find_users <- function(statuses,
                       followers,
                       favourites,
                       tweet_data) {

    # find all users that meet the above criteria:


    # use the 'unique()' function to make sure you only return a vector of
    # unique usernames:
    users <- unique(users)

}

# To create this program, it will be helpful to use the following trick. If we
# initialize users to NULL, then we can keep adding on usernames to it with the
# 'c()' operator as we find them, and the NULL will disappear as soon as we
# find valid matches. For example:
users <- NULL

# Print it out:
print(users)

# Now concatenate a name onto the end:
users <- c(users, "Matt")

# Print it out:
print(users)

# And we see that the "NULL" has disappeared. This is an easy way to make an
# expanding vector to store matches in.

# Once you have created your function, use it to find the user that matches
# these stats:
find_users(statuses = 62585,
           followers = 287180,
           favourites = 173,
           tweet_data = synthetic_tweets)



### Exercise 4 ###

# I am going to give you less direction in this final exercise. You should write
# a function that takes an input term and returns the number of unique users
# that included the term in at least one tweet, and their average number of
# followers. Remember that there may be multiple tweets by the same account, so
# you will need to find the unique users, and then get their average number of
# followers. Return these two values in a numeric vector of the form:
# c(number_of_users,average_followers). Try it out with "fake news".
